### ISSUE TITLE
wxFormBuilder Tidy up: Climatology dropdown does not work

### ISSUE THREAD

**Issue by rgleason** [rgleason/weather_routing_pi#68]
See new branch master-updates where it is building  v1.3.20.1
https://github.com/rgleason/weather_routing_pi/tree/master-update

Should deploy here  https://cloudsmith.io/~opencpn/repos/weather-routing-alpha/packages/

@thomtraub   Do you think you can fix this and checkk the other functions too?  Thanks.
NOTE  use master-update branch I''ve updated Frontend

Then I can rebuild and push to plugins for PIM

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ThomTrab** [comment]
Of course I will look at it. 
But can you be a little more specific on the issue ? On my side it seems to be working. By the way, you need to have the Climatology plugin installed and activated for this dropdown menu to be activated.
![image](https://user-images.githubusercontent.com/9775724/120933126-f2a4ae80-c6f8-11eb-9136-53fd841dd08a.png)

**Comment by rgleason** [comment]
ThomTraub, 
Sorry, I had disabled Climatology to test another plugin!  That was the problem.  
I am going to check that the current settings are still saved and then I think we are clear to push to PIM, but I am having trouble with Flatpak builds now.... going to close this now..
Thanks.
