### ISSUE TITLE
Installation: Copy of files from appdata to programdata not complete.

### ISSUE THREAD

**Issue by rgleason** [rgleason/weather_routing_pi#75]
Involves:
- weather_routing_pi/data/polars
- weather_routing_pi/data/polars/Example    
       - should example be changed to lower case? if so, boat files will have to change.
- weather_routing_pi/data/boat
- All polar files after Arcona_340 are not copied.

Polar file problems copying from 
```
%localappdata%/opencpn/plugins/weather_routing_pi/data/polars 
to   
programdata/opencpn/plugins/weather_routing/data/polars

https://www.cruisersforum.com/forums/f134/weather-routing-100060.html#post3457214

**Comment by soggygeek** [comment]
Actually, what happens is that OpenCPN crashes during the copy, and therefore the copy doesn't finish.  It crashes at the same place during the copy every time...before the Examples folder is copied and before the WeatherRoutingConfiguration.xml file.  This makes a new install of Weather Routing completely unusable.

**Comment by rgleason** [comment]
"This makes a new install of Weather Routing completely unusable."
I disagree, from my experience restart Opencpn and continue.

**Comment by rgleason** [comment]
WR still has some bugs see these Issues in particular, this one
WeatherRouting.cpp  line 147 -  228   //if boats or polars directories did not previously exist populate them.
Why does line 168 not copy all polars and stops at arcadia_340.pol? See Issue here
   -  if (forceCopyPolars)
        CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);
Is this plugin using the correct routine to copy from write only to user writable as required by flatpak?
Is this plugin using getPrivateApplicationDataLocation as is necessary for flatpak?
Will this plugin copy polars/Example/ directory in its entirety?
How can we get a  Main window > Configuration dropdown > "Reset Examples"  to default, selection? which will allow the User to select when to reset the examples provided.
I confirm that this plugin is using Search "getpPrivateApplicationDataLocation" in  weather_routing_pi.cpp
    Line 553:     wxString stdPath  = *GetpPrivateApplicationDataLocation();
Search "getPluginDataDir" (8 hits in 3 files of 28 searched)
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\BoatDialog.cpp (1 hit)
    Line 1018:         wxString message, generic_polar_path = GetPluginDataDir("weather_routing_pi")
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\icons.cpp (1 hit)
    Line 27:     fn.SetPath(GetPluginDataDir("weather_routing_pi"));
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\WeatherRouting.cpp (6 hits)
    Line 167:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);
    Line 169:         CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);
    Line 208:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/boats"), boatsdir);
    Line 209:                 CopyDataFiles(GetPluginDataDir("weather_routing_pi") + _T("/data/polars"), polarsdir);
    Line 212:             wxString cfg = GetPluginDataDir("weather_routing_pi") + _T("/data/") + _T("WeatherRoutingConfiguration.xml");
    Line 1580:     wxString infolocation = GetPluginDataDir("weather_routing_pi")

Search "getpPrivateApplicationDataLocation" (1 hit in 1 file of 28 searched)
  C:\Users\Rick\Documents\GitHub\weather_routing_pi\src\weather_routing_pi.cpp (1 hit)
    Line 553:     wxString stdPath  = *GetpPrivateApplicationDataLocation();

**Comment by rgleason** [comment]
In looking at the actual polar files, they appear to be well formed, but the file names start to have things like "...110%=jib.pol.
at the same point that the plugin falls.

I think we have to remove % from all the file names because that is not an allowed character.  This will probably fix the problem.

**Comment by rgleason** [comment]
Fixed Polar Names
https://github.com/rgleason/weather_routing_pi/commit/fff17b84333d0822a85b7499f0c497af2479eae3
