### ISSUE TITLE
Broken URLs in current catalog

### ISSUE THREAD

**Issue by leamas** [rgleason/weather_routing_pi#76]
As heading says: One broken weatherrouting url in current catalog.  

check logfile:  [urlcheck.log](https://github.com/rgleason/weather_routing_pi/files/6938963/urlcheck.log)

**Comment by rgleason** [comment]
That is a pretty amazing checker.
We have moved on to v1.13.30.2 now so what is needed here?
I thought this was being checked by the scripts in OpenCPN/plugiins?


2 urls checked, 0 errors
======> Checking metadata/weather_routing_pi-1.13.30.0-darwin-x86_64-11.4-macos.xml
.Ehttps://dl.cloudsmith.io/public/opencpn/weather-routing-prod/raw/names/weather_routing_pi-1.13.30.0-darwin-x86_64-11.4-macos-tarball/versions/v1.13.30.0/weather_routing_pi-1.13.30.0-darwin-x86_64-11.4-macos.tar.gz: 404

2 urls checked, 1 errors
======> Checking metadata/weather_routing_pi-1.13.30.0-debian-x86_64-10-buster.xml

**Comment by leamas** [comment]
As Jon have explained, urls are not checked by the script at OpenCPN/plugiins. He also claims (and I agree) that it isn't possible for performance reasons.

Which leaves us with the pre-commit hook -- it should check each and every url before it's committed. If you used that hook, the explanation is that the tarball at cloudsmith no longer is available for some reason.

**Comment by leamas** [comment]
> We have moved on to v1.13.30.2 

The check is run on current catalog which obviously is 1.13.30.0. 

The important thing here is not the broken url, it the fact that we have (had?) a process which commits broken urls into the catalog.  We really need to come to a point where just don't happens.

**Comment by rgleason** [comment]
I am sorry I was not paying attention to that discussion.
How can I use the hook?

`If you used that hook, the explanation is that the tarball at cloudsmith no longer is available for some reason.`

**Comment by leamas** [comment]
Work in the plugins project, easiest in git-bash.

  1.  Checkout master branch
  2.  Update to latest version using git pull or (better) git rebase.
  3. Copy the pre-commit hook to location where it's used:
             $ cp pre-commit .git/hooks

**Comment by leamas** [comment]
> I used to run a checker that checked all urls.

The hook is so much better. It only checks the updated urls, so it's reasonably fast. And it's run automatically when doing `git commit`.

**Comment by rgleason** [comment]
Yes, now I remember this technique. You had me do it for ocpn-manuals to check for line endings. It was a pain at first.

**Comment by rgleason** [comment]
WR has been removed and a new version added later.
