### ISSUE TITLE
Out of topic : this concerns your repository for oesenc_pi where there is no issues tab

### ISSUE THREAD

**Issue by filochard** [rgleason/weather_routing_pi#82]
Hi Rick

Back again for a problem with oesenc_pi

Since unfortuantely  we couldn't build anything from bdbcat's repository, 
he told me that we could use your repository because the oeserverd was the same on your repository and his one, and there were no important changes beside this ...

I could build a rpm for Mageia with your code source since the README.md had been updated by Alec (clearly allowing copies of the closed source binaries and libraries) Now we can propose this plugin for Mageia 

But 2 month ago bdbcat has updated the oeserverd binary for 
linux 64      https://github.com/bdbcat/oesenc_pi/tree/master/libs/oeserverd/linux64
armf           https://github.com/bdbcat/oesenc_pi/tree/master/libs/oeserverd/linuxarm
arm64        https://github.com/bdbcat/oesenc_pi/tree/master/libs/oeserverd/linuxarm64
And we still can't build anything from his repository (he intends to only work for the plugin manager or flatpak )
I didn't find any workaround 
He didn't modify oeserverd for linux 32 (thinking it's useless nowadays)

Would it be possible for you to import those oeserverd binary in your repository, respectively to : 
https://github.com/rgleason/oesenc_pi/tree/master/buildlinux64/oeserverd
https://github.com/rgleason/oesenc_pi/tree/master/buildlinuxarm/oeserverd
https://github.com/rgleason/oesenc_pi/tree/master/buildlinuxarm64/oeserverd
So that we may easily build packages (rpms or deb or .exe) for a legacy installation 

NB the tree of bdbcat has been modified since you forked it and the binaries are not in the same folders as yours

**Comment by rgleason** [comment]
Hi
I cloned oesenc_pi some time ago to use it as a model to update VDR_pi.  I may have worked on oesenc a little too, but I am pretty sure it is not up to date with Dave' version as I have not paid attention to it.

To answer your question, yes I can do that, perhaps in a new branch?  
I won't be able to give much support after that as it is pretty foreign to me and I am busy on PI Documentation right now.

**Comment by filochard** [comment]
Hi 
Thanks for your quick answer

I don't think you must create a new branch but a new tag in master and increase the VERSION.cmake to a version higher than 4.2.15   maybe 4.2.16 ? 
 (bdbcat's last VERSION.cmake is 4.2.20.0 but it includes several other changes concerning flatpak build, circleci that are not necessary to build a legacy package)

Only mention that you update oeserverd to version 1.20 from bdbcat for each concerned architecture 

Thanks for your work on the other plugins for flatpak  :  it's nearly as useable as a legacy rpm install now
(logbook watchdog radar ...)

**Comment by rgleason** [comment]
Filochard, I just looked at doing this and found that I had cleaned out my local repository of plugins I was no longer using, so I will have to clone my remote repository.

Why don't you try forking my remote build to your own remote github repository, then clone the plugin down to your local computer so you can work on it and make those changes? Then you would git add the changes and git commit them and then git push them back up to your remote.  It isn't that hard to do and I think you have the job well in hand.  

If you have trouble or don't wantt to do it I can.

**Comment by filochard** [comment]
Thanks for your advise
I forked your repository and updated the oeserverd binaries copying them from bdbcat repository
https://github.com/filochard/oesenc_pi
Now I can build rpms for Mageia

**Comment by rgleason** [comment]
That is great!!  Good job.
